language: node_js
node_js:
- 13.8.0
cache: npm
jobs:
  include:
  - stage: test
    script:
    - echo 'Deploy!!'
    - echo 'Installing Deps!'
  - stage: deploy
    script:
    - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out deploy_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 deploy_rsa
    - ssh-add deploy_rsa
    - ssh -o "StrictHostKeyChecking=no" $USERNAME@$HOST "cd mongosync && git pull && /home/genadyne/.nvm/versions/node/v12.18.0/bin/pm2 restart 0"
